export const events = [
  {
    image: "/images/event1.png",
    title: "React Summit 2024",
    slug: "react-summit-2024",
    location: "Amsterdam, Netherlands",
    date: "June 14-18, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    image: "/images/event2.png",
    title: "AWS re:Invent",
    slug: "aws-reinvent-2024",
    location: "Las Vegas, NV",
    date: "December 2-6, 2024",
    time: "8:00 AM - 8:00 PM",
  },
  {
    image: "/images/event3.png",
    title: "GitHub Universe",
    slug: "github-universe-2024",
    location: "San Francisco, CA",
    date: "October 29-30, 2024",
    time: "9:00 AM - 5:00 PM",
  },
  {
    image: "/images/event4.png",
    title: "DevFest 2024",
    slug: "devfest-2024",
    location: "Multiple Cities",
    date: "November 2024",
    time: "10:00 AM - 6:00 PM",
  },
  {
    image: "/images/event5.png",
    title: "HackMIT",
    slug: "hackmit-2024",
    location: "Cambridge, MA",
    date: "September 14-15, 2024",
    time: "24 Hours",
  },
  {
    image: "/images/event6.png",
    title: "Next.js Conf",
    slug: "nextjs-conf-2024",
    location: "San Francisco, CA",
    date: "October 24, 2024",
    time: "10:00 AM - 4:00 PM",
  },
];
